### ISSUE TITLE
242 Translated Title issues

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/bibframe2marc-xsl#12]
The specifications used to have a block for the 242, but it wasn't migrated over in the update from multiple sheets to a single sheet. [Here's the 1.0 spec.](https://github.com/lcnetdev/bibframe2marc/blob/9b726ac08cf7e8d601bf37519a169eace81ebfc8/specs/bf2marcSpec-200-247-v1.0.xlsx)

The 242 code [here](https://github.com/lcnetdev/bibframe2marc/blob/master/rules/05-2XX.xml#L108-L125)  is missing the $y for the language code. The language code is required along with $a. This is related to [this issue](https://github.com/lcnetdev/marc2bibframe2/issues/223) where the $y is ignored when creating a translated title.

**Comment by kefo** [comment]
https://github.com/lcnetdev/bibframe2marc/commit/62c4c51611a1e27660e8a358f45538f81f75072d
