### ISSUE TITLE
Switch bflc:Eidr to bf:Eidr?

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/bibframe2marc-xsl#14]
The Eidr class is a little odd since it has both a bflc and a bf version:
http://id.loc.gov/ontologies/bflc/Eidr
http://id.loc.gov/ontologies/bibframe/Eidr

See https://github.com/lcnetdev/bibframe-ontology/issues/78

In the bf2marc conversion it refers to the bflc version defining the indicator and then both when populating the $2:

[bflc](https://github.com/lcnetdev/bibframe2marc/blob/027d24b7a86d855b7e3a50898a6005237273f2bf/rules/02-010-048.xml#L224)

[bflc and bf](https://github.com/lcnetdev/bibframe2marc/blob/027d24b7a86d855b7e3a50898a6005237273f2bf/rules/02-010-048.xml#L260)

A few different ways to go - it seems like the bflc version could be deprecated and you could just use bf:Eidr?

**Comment by jodiw01** [comment]
The bf2marc conversion specs only use bf:Eidr. Looks like the conversion needs to be updated to match.

**Comment by jodiw01** [comment]
This issue has been fixed in marc2bibframe v2.5
