### ISSUE TITLE
 zip release tagged as 2.3 

### ISSUE THREAD

**Issue by jimfhahn** [lcnetdev/bibframe2marc-xsl#15]
I downloaded the zip release that is available on the 2.4 release page: https://github.com/lcnetdev/bibframe2marc/releases/tag/v.2.4.0

 When it is built, I see it has   <xsl:variable name="vCurrentVersion">DLC bibframe2marc v2.3.0</xsl:variable>

Wondering if there is a tag that needs updating for the 2.4 release?

**Comment by kirkhess** [comment]
Hi Jim - the file rules/VERSION needs the version bumped up to 2.4.0

**Comment by kirkhess** [comment]
I created a Pull request...

**Comment by kefo** [comment]
I'm going to close this. 

I did not issue a new release to account for the incorrect version tag.  I hope that is OK since 2.4 has not been superseded by 2.5, which I just pushed out.

Open if we need to actually get this corrected.
