### ISSUE TITLE
add DLC uri to xsl:message

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe2marc-xsl#3]
Request for a further refinement to record ID in xsl:message change:

The xpath in compile.xsl https://github.com/lcnetdev/bibframe2marc-xsl/blob/rules/src/compile.xsl
is looking for bf:Source/rdfs:label “DLC” instead of <bf:Source rdf:about="http://id.loc.gov/vocabulary/organizations/dlc" />

bf:Source/rdfs:label "DLC" should remain, but bf:Source rdf:about="http://id.loc.gov/vocabulary/organizations/dlc" should be added

**Comment by wafschneider** [comment]
Good catch, @jodiw01 -- in addition, I added a match for `<bf:source rdf:resource="http://id.loc.gov/vocabulary/organizations/dlc"/>`
