### ISSUE TITLE
strange 001 value

### ISSUE THREAD

**Issue by ucblawlib** [lcnetdev/bibframe2marc-xsl#31]
I'm using Sinopia to create RDF-XML, then using bibframe2marc for the transform. 

- In cases where my BIBFRAME has a value for bf:AdminMetadata/bf:identifiedBy/bf:Local/rdf:value, that value is propagated to the MARC 001.
- However, in cases where my BIBFRAME does not have this property, a MARC 001 is generated with a value of "d0e1". 

Why is this 001 created this way, in the latter case?
Thank you!
Michael Lindsey
UC Berkeley Law Library
mlindsey@berkeley.edu

**Comment by ntra00** [comment]
According to the README, if you don't supply one the recordId gets the value of the xslt function generate-id(), which produces and ID based on the xml node it's processing at the time.
https://github.com/lcnetdev/bibframe2marc/blob/c93c304dfef4daac9c703e4065eb3e9bdd0b7e45/README.md?plain=1#L56

**Comment by ucblawlib** [comment]
aha, thank you Nate. If I always using the same mode, can I expect this value to remain the same over time? I'll look into the generate-id() function today.

**Comment by ntra00** [comment]
It's internally consistent to the current document, but random, so I doubt it, even though it should be always generating on the root node..

**Comment by ucblawlib** [comment]
I've found a way to account for this in my application logic. I appreciate the co-operation on this. Thanks Nate!
Michael
